# NumPy Indexing

In [1]:
import numpy as np 

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[4]

4

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:5]   # all before 5

array([0, 1, 2, 3, 4])

In [8]:
arr[5:] # all after 5 

array([ 5,  6,  7,  8,  9, 10])

## broadcasting

In [9]:
arr[:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
slice_of_arr = arr[:6]

In [18]:
slice_of_arr  # this does not copying but viewing a part of arr. changed in slice.. will effect arr.

array([100, 100, 100, 100, 100,   5])

In [19]:
slice_of_arr[:] = 11 # all members of the sliced array is 11

In [21]:
arr   # the original array is also changed. !!! not only the slice but also the original arr has changed

array([11, 11, 11, 11, 11, 11,  6,  7,  8,  9, 10])

In [22]:
# slice does not copy
# to copy need to use copy method specifically

arr_copy = arr.copy()

In [24]:
arr_copy    # it is copied

array([11, 11, 11, 11, 11, 11,  6,  7,  8,  9, 10])

## 2D indexing

In [27]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
arr_2d[0][0]  # first row first column

5

In [31]:
arr_2d[0]   # the entire row 0

array([ 5, 10, 15])

In [32]:
arr_2d[1][1]

25

In [34]:
arr_2d[1,1] # instead of double brackets we can also use comma

25

In [35]:
arr_2d[1,2]  # second row third column

30

In [36]:
arr_2d[:2,1:]  # grabbed the right top corner

array([[10, 15],
       [25, 30]])

In [37]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [38]:
ar = np.random.randint(1,100,25)

In [39]:
ar

array([26, 52,  2, 55, 32, 84, 68, 97, 93, 83, 77, 27, 97, 47, 29, 68, 37,
       97, 17, 33, 79, 82, 29, 89, 35])

In [44]:
ar=ar.reshape(5,5)  # if not reassign it does not work. it will be just a view

In [46]:
ar[1:3,3:]

array([[93, 83],
       [47, 29]])

## conditional selection

In [47]:
arr = np.arange(0,11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr > 5   # boolean result

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [50]:
arr<3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False])

In [52]:
bool_array = arr > 5

In [53]:
bool_array

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [54]:
arr[bool_array]  # we can select booleans in this way

array([ 6,  7,  8,  9, 10])

In [55]:
arr[arr<4]  # a different selection of boolean. we put the condition in brackets

array([0, 1, 2, 3])

In [56]:
arr[arr]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## NumPy Operations 

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [59]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [73]:
# normally 0/0 is non defined. but numpy gives a nan value instead of an error unlike python
arr/arr  

/Users/Latif/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [74]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [75]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [76]:
arr + arr*2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
1/0   # zero division error but numpy gives nan

ZeroDivisionError: division by zero

In [80]:
1/arr    # same 0 division warning.

/Users/Latif/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [81]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## universal array functions

In [83]:
np.sqrt(arr)   # square root of array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [84]:
np.exp(arr)   # calculating exponential e^ of array

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [85]:
np.max(arr)

10

In [86]:
arr.max()

10

In [87]:
np.min(arr)

0

In [89]:
np.sin(arr)  # sinüs

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [90]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [91]:
np.log(arr)

/Users/Latif/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])