In [73]:
import numpy as np

In [74]:
my_list = [1,2,3]

In [75]:
arr = np.array(my_list)

In [76]:
arr

array([1, 2, 3])

In [77]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [78]:
mat = np.matrix(my_mat)

In [79]:
mat

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### there is better ways to create arrays and matrixes

In [81]:
np.arange(0,11,2) # start, stop, step.   like range func of python. stop excluded

array([ 0,  2,  4,  6,  8, 10])

In [84]:
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

In [85]:
np.zeros(3)

array([0., 0., 0.])

In [87]:
np.zeros((5,5))       # because we are passing a tuple there is two pairs of paranthesis. one is tuple's.

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [88]:
np.ones(4)    # a one dimensional

array([1., 1., 1., 1.])

In [89]:
np.ones((3,4))   # with a tuple 3x4 dimensional

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [91]:
np.ones((3,4))*5   # we can use ones to create other numbers filled matrixes

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

###  linspace()

In [92]:
np.linspace(0,4,6)   # I want 6 numbers from 0 to 4 equally dvided.

array([0. , 0.8, 1.6, 2.4, 3.2, 4. ])

In [94]:
np.arange(0,5,2)   # o to 5, 2 by 2

array([0, 2, 4])

In [95]:
np.linspace(0,5,2)  # 0 to 5, 2 numbers equallt divided

array([0., 5.])

In [97]:
np.linspace(0,5,100)    # 100 numbers in a one dimensonal array. 

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

### Identity Matrix 

In [98]:
np.eye(5)     # a 5x5 identity matrix.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random Numbers

###  random.rand(d0,d1..)      uniform distirbution 

In [99]:
np.random.rand(5)    # 5 numbers from uniform distribution

array([0.3619068 , 0.84240419, 0.75480409, 0.6069035 , 0.93073363])

In [100]:
np.random.rand(5,2)   # a 2 dimensional matrix.

array([[0.04961478, 0.24568482],
       [0.30426184, 0.43634888],
       [0.02308517, 0.27407955],
       [0.17625874, 0.21224585],
       [0.90161165, 0.13360165]])

In [101]:
np.random.rand(50)    # a one dimensional array of 50 numbers from unifor distribution

array([0.13941567, 0.42017438, 0.096874  , 0.90146353, 0.0741587 ,
       0.42064521, 0.1491175 , 0.41140761, 0.19894333, 0.74547267,
       0.71874302, 0.57353671, 0.79691729, 0.06948842, 0.69000897,
       0.69135435, 0.98068026, 0.55694765, 0.04892477, 0.81096128,
       0.99171181, 0.02507597, 0.96895512, 0.64853871, 0.89196524,
       0.03796045, 0.2970236 , 0.53049964, 0.0216426 , 0.99473191,
       0.00224587, 0.77212997, 0.66125529, 0.52927735, 0.13352255,
       0.12627377, 0.87129618, 0.21258751, 0.93500098, 0.42017098,
       0.5466172 , 0.80066162, 0.38098826, 0.68851994, 0.37626639,
       0.07678192, 0.2551015 , 0.76575959, 0.62195126, 0.8708539 ])

### random.randn()           
 - appropriate to normal distibution

In [111]:
np.random.randn(2)

array([-0.10802429, -0.69711449])

In [112]:
np.random.randn(20)

array([ 0.04393949, -0.68206295, -0.55512125,  1.5288668 , -2.16935589,
        1.54460189,  0.18628195,  0.61972386, -0.95173133,  0.83309053,
        0.51655851,  0.86492433, -0.07768057,  1.02238019, -1.11605122,
       -0.79100982, -0.31845453,  0.37386967, -1.38338924, -0.67934293])

### random.randint() 

In [121]:
np.random.randint(3) # from [0,3)  from low to high. default 1 random number

1

In [123]:
np.random.randint(0,6)  # from [0,6).  

4

In [124]:
np.random.randint(0,60) 

47

In [125]:
np.random.randint(0,60,5) # from [0,60) 5 random numbers

array([46, 53, 10, 23, 50])

In [127]:
arr = np.arange(25)   #. in order 25 numbers in an array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [129]:
ranarr = np.random.randint(0,25,10)    # randomly selected 10 numbers between 0 and 25
ranarr 

array([ 1, 16, 18,  4,  2, 18, 14,  1,  2, 14])

###  reshape ( )

In [130]:
arr.reshape(5,5)    #reshapes one dimensional array to a two dimensional array. dimensions must be convenient

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [136]:
ranarr

array([ 1, 16, 18,  4,  2, 18, 14,  1,  2, 14])

In [137]:
ranarr.max()   # max value in the list

18

In [138]:
ranarr.min()  # min value in the list

1

In [140]:
ranarr.argmax()  # index of the max value

2

In [141]:
ranarr.argmin()  # index of the min value

0

In [143]:
 arr.shape   # 25, means one dimensional.

(25,)

In [146]:
arr = arr.reshape(5,5)   # reshaped to a 2 dimensional matrix
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [147]:
arr.shape    # shape is now 5x5

(5, 5)

In [148]:
arr.dtype

dtype('int64')